spring.application.name=backend
openai.api.key=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
azure.blob.connection-string=DefaultEndpointsProtocol=https;AccountName=koladechatbot;AccountKey=1AKQWwKEePY7w1YVIrQe7gw24zBPuXKfqH2g9WcigbxFskwaUN20Lc2b+ROd1GQVEHbMve2rCsjN+AStcDt+Uw==;EndpointSuffix=core.windows.net
